# syntax=docker/dockerfile:1

FROM ubuntu:24.04 AS workspace

# Install dependencies
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm --force /etc/apt/apt.conf.d/docker-clean \
    && echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' \
        > /etc/apt/apt.conf.d/keep-cache \
    && export DEBIAN_FRONTEND=noninteractive \
    && dpkg --add-architecture i386 \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        cabextract \
        rename \
        unzip \
        wine32:i386 \
        wine64 \
        winetricks \
        xvfb

# Set up the Wine environment as a non-root user
USER ubuntu:ubuntu
WORKDIR /home/ubuntu

ENV WINEARCH=win64
ENV WINEPREFIX=/home/ubuntu/.wine64

ADD --chown=ubuntu:ubuntu \
    https://builds.dotnet.microsoft.com/dotnet/Runtime/6.0.36/dotnet-runtime-6.0.36-win-x64.exe \
    dotnet-runtime-6.0.36-x64.exe

ADD --chown=ubuntu:ubuntu \
    https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/6.0.36/aspnetcore-runtime-6.0.36-win-x64.exe \
    aspnetcore-runtime-6.0.36-x64.exe

# Install .NET 6.0 and ASP.NET Core 6.0
RUN xvfb-run -a sh -c "\
        wineboot --init \
        && winetricks -q dotnet6 \
        && wine dotnet-runtime-6.0.36-x64.exe /quiet /norestart \
        && wine aspnetcore-runtime-6.0.36-x64.exe /norestart /quiet \
    "

FROM workspace AS runner

ARG DUMP_FILE="FiveNightsatFreddys.exe"
ARG DUMP_NAME="Five Nights at Freddys"

WORKDIR /CTFAK.Cli
COPY --chown=ubuntu:ubuntu CTFAK.Cli ./
COPY --chown=ubuntu:ubuntu ${DUMP_FILE} ./
RUN wine ./CTFAK.Cli.exe \
        -path "${DUMP_FILE}" \
        -closeonfinish \
        -tool "Image Dumper" "Sound Dumper" \
    && cd "Dumps/${DUMP_NAME}/Sounds" \
    && rename 's/ /_/g' *

FROM scratch AS out

ARG DUMP_NAME="Five Nights at Freddys"
COPY --from=runner "/CTFAK.Cli/Dumps/${DUMP_NAME}/" /dump/
