# syntax=docker/dockerfile:1

FROM ubuntu:24.04 AS build

ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update --assume-yes \
    && apt-get install --assume-yes --no-install-recommends \
        ca-certificates \
        curl \
        libicu-dev \
        unzip \
    && curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh \
    && bash dotnet-install.sh --channel 6.0 --install-dir /usr/share/dotnet \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

USER ubuntu:ubuntu
WORKDIR /CTFAK2.0
COPY --chown=ubuntu:ubuntu CTFAK2.0 ./
COPY --chown=ubuntu:ubuntu ctfakrequirements.zip ./

RUN dotnet restore CTFAK.sln \
    && dotnet build Core/CTFAK.Core/CTFAK.Core.csproj -c Release -p:EnableWindowsTargeting=true --runtime win-x64 --self-contained true \
    && dotnet build Interface/CTFAK.Cli/CTFAK.Cli.csproj -c Release -p:EnableWindowsTargeting=true --runtime win-x64 --self-contained true \
    && dotnet build Plugins/CTFAK.Decompiler/CTFAK.Decompiler.csproj -c Release -p:EnableWindowsTargeting=true --runtime win-x64 --self-contained true \
    && dotnet build Plugins/Dumper/Dumper.csproj -c Release -p:EnableWindowsTargeting=true --runtime win-x64 --self-contained true \
    && mkdir Interface/CTFAK.Cli/bin/Release/net6.0-windows/win-x64/Plugins \
    && cp --archive \
        Plugins/CTFAK.Decompiler/bin/Release/net6.0-windows/win-x64/CTFAK.Decompiler.dll \
        Plugins/CTFAK.Decompiler/bin/Release/net6.0-windows/win-x64/CTFAK.Decompiler.pdb \
        Plugins/Dumper/bin/Release/net6.0-windows/win-x64/Dumper.dll \
        Plugins/Dumper/bin/Release/net6.0-windows/win-x64/Dumper.pdb \
        Interface/CTFAK.Cli/bin/Release/net6.0-windows/win-x64/Plugins/ \
    && cp --archive \
        Core/CTFAK.Core/bin/Release/net6.0-windows/win-x64/CTFAK.Core.dll \
        Core/CTFAK.Core/bin/Release/net6.0-windows/win-x64/CTFAK.Core.pdb \
        Interface/CTFAK.Cli/bin/Release/net6.0-windows/win-x64/ \
    && unzip ctfakrequirements.zip -d Interface/CTFAK.Cli/bin/Release/net6.0-windows/win-x64/

FROM scratch AS out

COPY --from=build /CTFAK2.0/Interface/CTFAK.Cli/bin/Release/net6.0-windows/win-x64 /CTFAK.Cli
